/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author USUARIO
 */
public class VistaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form Perfil
     */
    public VistaPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
        ImageIcon imagen = new ImageIcon(getClass().getResource("/Imagenes/logo1.png"));
        Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(logoApp_lbl.getWidth(), logoApp_lbl.getHeight(), Image.SCALE_DEFAULT));
        logoApp_lbl.setIcon(icono);
        ImageIcon imagen2 = new ImageIcon(getClass().getResource("/Imagenes/chat.png"));
        Icon icono2 = new ImageIcon(imagen2.getImage().getScaledInstance(jBChat.getWidth(), jBChat.getHeight(), Image.SCALE_DEFAULT));
        jBChat.setIcon(icono2);
        ImageIcon imagen3 = new ImageIcon(getClass().getResource("/Imagenes/calendar.png"));
        Icon icono3 = new ImageIcon(imagen3.getImage().getScaledInstance(jBHorario.getWidth(), jBHorario.getHeight(), Image.SCALE_DEFAULT));
        jBHorario.setIcon(icono3);
        ImageIcon imagen5 = new ImageIcon(getClass().getResource("/Imagenes/user.png"));
        Icon icono5 = new ImageIcon(imagen5.getImage().getScaledInstance(jBPerfil.getWidth(), jBPerfil.getHeight(), Image.SCALE_DEFAULT));
        jBPerfil.setIcon(icono5);
        ImageIcon imagen6 = new ImageIcon(getClass().getResource("/Imagenes/exit.png"));
        Icon icono6 = new ImageIcon(imagen6.getImage().getScaledInstance(jBExit.getWidth(), jBExit.getHeight(), Image.SCALE_DEFAULT));
        jBExit.setIcon(icono6);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logoApp_lbl = new javax.swing.JLabel();
        jBHorario = new javax.swing.JButton();
        jBExit = new javax.swing.JButton();
        jBPerfil = new javax.swing.JButton();
        jBChat = new javax.swing.JButton();
        fondoPerfil_lbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoApp_lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo1.png"))); // NOI18N
        getContentPane().add(logoApp_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 230, 80));

        jBHorario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/calendar.png"))); // NOI18N
        getContentPane().add(jBHorario, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 60, 60));

        jBExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/exit.png"))); // NOI18N
        jBExit.setContentAreaFilled(false);
        jBExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExitActionPerformed(evt);
            }
        });
        getContentPane().add(jBExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 30, 60, 60));

        jBPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/user.png"))); // NOI18N
        jBPerfil.setContentAreaFilled(false);
        jBPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPerfilActionPerformed(evt);
            }
        });
        getContentPane().add(jBPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, 60, 60));

        jBChat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/chat.png"))); // NOI18N
        jBChat.setContentAreaFilled(false);
        jBChat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBChatActionPerformed(evt);
            }
        });
        getContentPane().add(jBChat, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 60, 60));

        fondoPerfil_lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/wp4009285.jpg"))); // NOI18N
        getContentPane().add(fondoPerfil_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 130));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExitActionPerformed
        
    }//GEN-LAST:event_jBExitActionPerformed

    private void jBPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPerfilActionPerformed
        
    }//GEN-LAST:event_jBPerfilActionPerformed

    private void jBChatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBChatActionPerformed
        
    }//GEN-LAST:event_jBChatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fondoPerfil_lbl;
    public javax.swing.JButton jBChat;
    public javax.swing.JButton jBExit;
    public javax.swing.JButton jBHorario;
    public javax.swing.JButton jBPerfil;
    private javax.swing.JLabel logoApp_lbl;
    // End of variables declaration//GEN-END:variables
}
