/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author USUARIO
 */
public class VistaIngreso extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public VistaIngreso() {
        initComponents();
        this.setLocationRelativeTo(null);
        ImageIcon imagen = new ImageIcon(getClass().getResource("/Imagenes/wp4009285.jpg"));
        Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(fondo_lbl.getWidth(), fondo_lbl.getHeight(), Image.SCALE_DEFAULT));
        fondo_lbl.setIcon(icono);
        ImageIcon imagen2 = new ImageIcon(getClass().getResource("/Imagenes/user.png"));
        Icon icono2 = new ImageIcon(imagen2.getImage().getScaledInstance(usuario_lbl.getWidth(), usuario_lbl.getHeight(), Image.SCALE_DEFAULT));
        usuario_lbl.setIcon(icono2);
        ImageIcon imagen3 = new ImageIcon(getClass().getResource("/Imagenes/logo1.png"));
        Icon icono3 = new ImageIcon(imagen3.getImage().getScaledInstance(logoSergio_lbl.getWidth(), logoSergio_lbl.getHeight(), Image.SCALE_DEFAULT));
        logoSergio_lbl.setIcon(icono3);
        ImageIcon imagen4 = new ImageIcon(getClass().getResource("/Imagenes/lockoverlay.png"));
        Icon icono4 = new ImageIcon(imagen4.getImage().getScaledInstance(password_lbl.getWidth(), password_lbl.getHeight(), Image.SCALE_DEFAULT));
        password_lbl.setIcon(icono4);
        ImageIcon imagen5 = new ImageIcon(getClass().getResource("/Imagenes/delete.png"));
        Icon icono5 = new ImageIcon(imagen5.getImage().getScaledInstance(jBSalir.getWidth(), jBSalir.getHeight(), Image.SCALE_DEFAULT));
        jBSalir.setIcon(icono5);
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jBSalir = new javax.swing.JButton();
        logoSergio_lbl = new javax.swing.JLabel();
        jBIngresar = new javax.swing.JButton();
        jBRegistrar = new javax.swing.JButton();
        jTUsuario = new javax.swing.JTextField();
        jTContrasena = new javax.swing.JPasswordField();
        password_lbl = new javax.swing.JLabel();
        usuario_lbl = new javax.swing.JLabel();
        fondo_lbl = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/delete.png"))); // NOI18N
        jBSalir.setContentAreaFilled(false);
        jBSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jBSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, 30, 30));

        logoSergio_lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo1.png"))); // NOI18N
        getContentPane().add(logoSergio_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 420, 130));

        jBIngresar.setText("INGRESAR");
        jBIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBIngresarActionPerformed(evt);
            }
        });
        getContentPane().add(jBIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 150, 30));

        jBRegistrar.setText("REGISTRAR");
        jBRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(jBRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, 150, 30));
        getContentPane().add(jTUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 220, 30));
        getContentPane().add(jTContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 220, 30));
        getContentPane().add(password_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 50, 50));
        getContentPane().add(usuario_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 30, 30));

        fondo_lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/wp4009285.jpg"))); // NOI18N
        getContentPane().add(fondo_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBIngresarActionPerformed

    }//GEN-LAST:event_jBIngresarActionPerformed

    private void jBRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRegistrarActionPerformed

    }//GEN-LAST:event_jBRegistrarActionPerformed

    private void jBSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalirActionPerformed

    }//GEN-LAST:event_jBSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaIngreso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fondo_lbl;
    public javax.swing.JButton jBIngresar;
    public javax.swing.JButton jBRegistrar;
    public javax.swing.JButton jBSalir;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JPasswordField jTContrasena;
    public javax.swing.JTextField jTUsuario;
    private javax.swing.JLabel logoSergio_lbl;
    private javax.swing.JLabel password_lbl;
    private javax.swing.JLabel usuario_lbl;
    // End of variables declaration//GEN-END:variables
}
