/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author USUARIO
 */
public class VistaEditPerfil extends javax.swing.JFrame {

    /**
     * Creates new form EditPerfil
     */
    public VistaEditPerfil() {
        initComponents();
        this.setLocationRelativeTo(null);
        ImageIcon imagen = new ImageIcon(getClass().getResource("/Imagenes/logo1.png"));
        Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(logoApp_lbl.getWidth(), logoApp_lbl.getHeight(), Image.SCALE_DEFAULT));
        logoApp_lbl.setIcon(icono);
        ImageIcon imagen2 = new ImageIcon(getClass().getResource("/Imagenes/home.png"));
        Icon icono2 = new ImageIcon(imagen2.getImage().getScaledInstance(jBPrincipal.getWidth(), jBPrincipal.getHeight(), Image.SCALE_DEFAULT));
        jBPrincipal.setIcon(icono2);
        ImageIcon imagen3 = new ImageIcon(getClass().getResource("/Imagenes/borrar.png"));
        Icon icono3 = new ImageIcon(imagen3.getImage().getScaledInstance(jBBorrar.getWidth(), jBBorrar.getHeight(), Image.SCALE_DEFAULT));
        jBBorrar.setIcon(icono3);
        ImageIcon imagen5 = new ImageIcon(getClass().getResource("/Imagenes/user.png"));
        Icon icono5 = new ImageIcon(imagen5.getImage().getScaledInstance(JBPerfil.getWidth(), JBPerfil.getHeight(), Image.SCALE_DEFAULT));
        JBPerfil.setIcon(icono5);
        JBPerfil.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logoApp_lbl = new javax.swing.JLabel();
        jBPrincipal = new javax.swing.JButton();
        fondoPerfil_lbl = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jBEditarPerfil = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTUsuario = new javax.swing.JTextField();
        jTInstitucion = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jConstrasena2 = new javax.swing.JPasswordField();
        jConstrasena1 = new javax.swing.JPasswordField();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTCorreo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        JBPerfil = new javax.swing.JButton();
        jBBorrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoApp_lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo1.png"))); // NOI18N
        getContentPane().add(logoApp_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 340, 60));

        jBPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/home.png"))); // NOI18N
        jBPrincipal.setContentAreaFilled(false);
        jBPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPrincipalActionPerformed(evt);
            }
        });
        getContentPane().add(jBPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 50, 50));

        fondoPerfil_lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/wp4009285.jpg"))); // NOI18N
        getContentPane().add(fondoPerfil_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 552, 80));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0), 8));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBEditarPerfil.setText("EDITAR PERFIL");
        jBEditarPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEditarPerfilActionPerformed(evt);
            }
        });
        jPanel2.add(jBEditarPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 420, 150, 40));

        jLabel9.setText("Contraseña:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 70, 30));

        jLabel8.setText("Usuario:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 50, 30));
        jPanel2.add(jTUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 180, 30));

        jTInstitucion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTInstitucionKeyTyped(evt);
            }
        });
        jPanel2.add(jTInstitucion, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 180, 30));

        jLabel7.setText("Institución:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 70, 30));

        jLabel10.setText("Contraseña:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 70, 20));
        jPanel2.add(jConstrasena2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, 180, 30));
        jPanel2.add(jConstrasena1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, 180, 30));

        jLabel11.setText("Confirmar");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, 70, 20));

        jLabel1.setText("Nombre:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 50, 30));

        jTNombre.setToolTipText("Nombre");
        jTNombre.setName(""); // NOI18N
        jTNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTNombreActionPerformed(evt);
            }
        });
        jTNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTNombreKeyTyped(evt);
            }
        });
        jPanel2.add(jTNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 180, 30));

        jLabel4.setText("Correo:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 50, 30));

        jTCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTCorreoActionPerformed(evt);
            }
        });
        jTCorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTCorreoKeyTyped(evt);
            }
        });
        jPanel2.add(jTCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 180, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Seguridad");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 210, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Datos Personales");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 210, -1));

        JBPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/user.png"))); // NOI18N
        JBPerfil.setContentAreaFilled(false);
        JBPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBPerfilActionPerformed(evt);
            }
        });
        jPanel2.add(JBPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 150, 140));

        jBBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/borrar.png"))); // NOI18N
        jBBorrar.setContentAreaFilled(false);
        jBBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBorrarActionPerformed(evt);
            }
        });
        jPanel2.add(jBBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 400, 60, 70));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 510, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBEditarPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEditarPerfilActionPerformed

    }//GEN-LAST:event_jBEditarPerfilActionPerformed

    private void jTInstitucionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTInstitucionKeyTyped

    }//GEN-LAST:event_jTInstitucionKeyTyped

    private void jTNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTNombreActionPerformed

    private void jTNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTNombreKeyTyped

    }//GEN-LAST:event_jTNombreKeyTyped

    private void jTCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTCorreoActionPerformed

    private void jTCorreoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTCorreoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTCorreoKeyTyped

    private void JBPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBPerfilActionPerformed

    }//GEN-LAST:event_JBPerfilActionPerformed

    private void jBPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPrincipalActionPerformed
        
    }//GEN-LAST:event_jBPrincipalActionPerformed

    private void jBBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBorrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBBorrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaEditPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaEditPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaEditPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaEditPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaEditPerfil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton JBPerfil;
    private javax.swing.JLabel fondoPerfil_lbl;
    public javax.swing.JButton jBBorrar;
    public javax.swing.JButton jBEditarPerfil;
    public javax.swing.JButton jBPrincipal;
    public javax.swing.JPasswordField jConstrasena1;
    public javax.swing.JPasswordField jConstrasena2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JTextField jTCorreo;
    public javax.swing.JTextField jTInstitucion;
    public javax.swing.JTextField jTNombre;
    public javax.swing.JTextField jTUsuario;
    private javax.swing.JLabel logoApp_lbl;
    // End of variables declaration//GEN-END:variables
}
