/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;


import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author USUARIO
 */
public class VistaHorario extends javax.swing.JFrame {

    /**
     * Creates new form Calendario
     */
    public VistaHorario() {
        initComponents();
        this.setLocationRelativeTo(null);
        ImageIcon imagen = new ImageIcon(getClass().getResource("/Imagenes/logo1.png"));
        Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(logoApp_lbl.getWidth(), logoApp_lbl.getHeight(), Image.SCALE_DEFAULT));
        logoApp_lbl.setIcon(icono);
        ImageIcon imagen2 = new ImageIcon(getClass().getResource("/Imagenes/home.png"));
        Icon icono2 = new ImageIcon(imagen2.getImage().getScaledInstance(jBInicio.getWidth(), jBInicio.getHeight(), Image.SCALE_DEFAULT));
        jBInicio.setIcon(icono2); 
        jCalendario.setDefaultEditor(Object.class, null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jCalendario = new javax.swing.JTable();
        logoApp_lbl = new javax.swing.JLabel();
        jBInicio = new javax.swing.JButton();
        fondoPerfil_lbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jCalendario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"   7 -  8 am", null, null, null, null, null, null},
                {"   8 -  9 am", null, null, null, null, null, null},
                {"   9 - 10 am", null, null, null, null, null, null},
                {" 10 - 11 am", null, null, null, null, null, null},
                {" 11 - 12 am", null, null, null, null, null, null},
                {" 12  -  1 pm", null, null, null, null, null, null},
                {"   1 -  2 pm", null, null, null, null, null, null},
                {"   2 -  3 pm", null, null, null, null, null, null},
                {"   3 -  4 pm", null, null, null, null, null, null},
                {"   4 -  5 pm", null, null, null, null, null, null},
                {"   5 -  6 pm", null, null, null, null, null, null},
            },
            new String [] {
                "Hora", "Lunes", "Martes", "Miercoles", "Jueves", "Viernes", "Sabado"
            }
        ));
        jCalendario.setCellSelectionEnabled(true);
        jCalendario.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jCalendario.setRowHeight(60);
        jScrollPane1.setViewportView(jCalendario);
        jCalendario.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 760, 310));

        logoApp_lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo1.png"))); // NOI18N
        getContentPane().add(logoApp_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 220, 60));

        jBInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/home.png"))); // NOI18N
        jBInicio.setContentAreaFilled(false);
        jBInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBInicioActionPerformed(evt);
            }
        });
        getContentPane().add(jBInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 10, 50, 50));

        fondoPerfil_lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/wp4009285.jpg"))); // NOI18N
        getContentPane().add(fondoPerfil_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 80));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBInicioActionPerformed

    }//GEN-LAST:event_jBInicioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaHorario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaHorario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaHorario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaHorario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaHorario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fondoPerfil_lbl;
    public javax.swing.JButton jBInicio;
    public javax.swing.JTable jCalendario;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logoApp_lbl;
    // End of variables declaration//GEN-END:variables
}
