/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;


import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author USUARIO
 */
public class VistaChat extends javax.swing.JFrame {

    /**
     * Creates new form Chat
     */
    public VistaChat() {
        initComponents();
        this.setLocationRelativeTo(null);
        ImageIcon imagen = new ImageIcon(getClass().getResource("/Imagenes/logo1.png"));
        Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(logoApp_lbl.getWidth(), logoApp_lbl.getHeight(), Image.SCALE_DEFAULT));
        logoApp_lbl.setIcon(icono);
        ImageIcon imagen2 = new ImageIcon(getClass().getResource("/Imagenes/email_send.png"));
        Icon icono2 = new ImageIcon(imagen2.getImage().getScaledInstance(jBEnviar.getWidth(), jBEnviar.getHeight(), Image.SCALE_DEFAULT));
        jBEnviar.setIcon(icono2);
        ImageIcon imagen3 = new ImageIcon(getClass().getResource("/Imagenes/home.png"));
        Icon icono3 = new ImageIcon(imagen3.getImage().getScaledInstance(jBPrincipal.getWidth(), jBPrincipal.getHeight(), Image.SCALE_DEFAULT));
        jBPrincipal.setIcon(icono3);
        jTAChat.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTAChat = new javax.swing.JTextArea();
        jTMensaje = new javax.swing.JTextField();
        jBEnviar = new javax.swing.JButton();
        jBPrincipal = new javax.swing.JButton();
        logoApp_lbl = new javax.swing.JLabel();
        fondoPerfil_lbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jCBContacto = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTAChat.setColumns(20);
        jTAChat.setRows(5);
        jScrollPane1.setViewportView(jTAChat);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 490, 230));
        getContentPane().add(jTMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 440, 30));

        jBEnviar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/email_send.png"))); // NOI18N
        jBEnviar.setContentAreaFilled(false);
        jBEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEnviarActionPerformed(evt);
            }
        });
        getContentPane().add(jBEnviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 360, 30, 30));

        jBPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/home.png"))); // NOI18N
        jBPrincipal.setContentAreaFilled(false);
        jBPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPrincipalActionPerformed(evt);
            }
        });
        getContentPane().add(jBPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 50, 50));

        logoApp_lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo1.png"))); // NOI18N
        getContentPane().add(logoApp_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 220, 60));

        fondoPerfil_lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/wp4009285.jpg"))); // NOI18N
        getContentPane().add(fondoPerfil_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 552, 80));

        jLabel1.setText("Online:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, 20));

        getContentPane().add(jCBContacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 120, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEnviarActionPerformed
        
    }//GEN-LAST:event_jBEnviarActionPerformed

    private void jBPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPrincipalActionPerformed

    }//GEN-LAST:event_jBPrincipalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaChat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fondoPerfil_lbl;
    public javax.swing.JButton jBEnviar;
    public javax.swing.JButton jBPrincipal;
    public javax.swing.JComboBox<String> jCBContacto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextArea jTAChat;
    public javax.swing.JTextField jTMensaje;
    private javax.swing.JLabel logoApp_lbl;
    // End of variables declaration//GEN-END:variables
}
