/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author USUARIO
 */
public class VistaRegistro extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public VistaRegistro() {
        initComponents();
        this.setLocationRelativeTo(null);
        ImageIcon imagen = new ImageIcon(getClass().getResource("/Imagenes/wp4009285.jpg"));
        Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(fondoInico_lbl.getWidth(), fondoInico_lbl.getHeight(), Image.SCALE_DEFAULT));
        fondoInico_lbl.setIcon(icono);
        ImageIcon imagen4 = new ImageIcon(getClass().getResource("/Imagenes/undo.png"));
        Icon icono4 = new ImageIcon(imagen4.getImage().getScaledInstance(jBIngreso.getWidth(), jBIngreso.getHeight(), Image.SCALE_DEFAULT));
        jBIngreso.setIcon(icono4);
        ImageIcon imagen5 = new ImageIcon(getClass().getResource("/Imagenes/delete.png"));
        Icon icono5 = new ImageIcon(imagen5.getImage().getScaledInstance(jBSalir.getWidth(), jBSalir.getHeight(), Image.SCALE_DEFAULT));
        jBSalir.setIcon(icono5);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jBCrearPerfil = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTUsuario = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTInstitucion = new javax.swing.JTextField();
        jTContrasena1 = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jTContrasena2 = new javax.swing.JPasswordField();
        jTCorreo = new javax.swing.JTextField();
        jTNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jBIngreso = new javax.swing.JButton();
        jBSalir = new javax.swing.JButton();
        fondoInico_lbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0), 8));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBCrearPerfil.setText("CREAR PERFIL");
        jBCrearPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCrearPerfilActionPerformed(evt);
            }
        });
        jPanel1.add(jBCrearPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 160, 40));

        jLabel9.setText("Contraseña:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 70, 30));

        jLabel8.setText("Nombre usuario:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 130, 30));
        jPanel1.add(jTUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 180, 30));

        jLabel7.setText("Institución:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 70, 30));
        jPanel1.add(jTInstitucion, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 180, 30));
        jPanel1.add(jTContrasena1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 180, 30));

        jLabel3.setText("Confirmar contraseña:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 140, 30));
        jPanel1.add(jTContrasena2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 180, 30));

        jTCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTCorreoActionPerformed(evt);
            }
        });
        jPanel1.add(jTCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 180, 30));
        jPanel1.add(jTNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 180, 30));

        jLabel4.setText("Correo:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 50, 30));

        jLabel1.setText("Nombre:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 50, 30));

        jBIngreso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/undo.png"))); // NOI18N
        jBIngreso.setContentAreaFilled(false);
        jBIngreso.setMaximumSize(new java.awt.Dimension(170, 170));
        jBIngreso.setMinimumSize(new java.awt.Dimension(170, 170));
        jBIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBIngresoActionPerformed(evt);
            }
        });
        jPanel1.add(jBIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 40, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 380, 370));

        jBSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/delete.png"))); // NOI18N
        jBSalir.setContentAreaFilled(false);
        jBSalir.setMaximumSize(new java.awt.Dimension(170, 170));
        jBSalir.setMinimumSize(new java.awt.Dimension(170, 170));
        jBSalir.setPreferredSize(new java.awt.Dimension(170, 170));
        jBSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jBSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, 30, 30));

        fondoInico_lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/wp4009285.jpg"))); // NOI18N
        getContentPane().add(fondoInico_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTCorreoActionPerformed

    private void jBCrearPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCrearPerfilActionPerformed

    }//GEN-LAST:event_jBCrearPerfilActionPerformed

    private void jBIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBIngresoActionPerformed

    }//GEN-LAST:event_jBIngresoActionPerformed

    private void jBSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalirActionPerformed

    }//GEN-LAST:event_jBSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaRegistro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fondoInico_lbl;
    public javax.swing.JButton jBCrearPerfil;
    public javax.swing.JButton jBIngreso;
    public javax.swing.JButton jBSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JPasswordField jTContrasena1;
    public javax.swing.JPasswordField jTContrasena2;
    public javax.swing.JTextField jTCorreo;
    public javax.swing.JTextField jTInstitucion;
    public javax.swing.JTextField jTNombre;
    public javax.swing.JTextField jTUsuario;
    // End of variables declaration//GEN-END:variables
}
